export const CATEGORIES = [
  "IT Project Management",
  "Data Analytics and Big Data",
  "Introduction to Process Management",
  "Business Administration I",
  "Business Administration II",
  "Cost and Performance Accounting II (Advanced)",
  "Requirements Engineering",
  "Quality Assurance in the Software Process",
  "Fundamentals of Object-Oriented Programming with Java",
  "Mathematics Basics I",
  "Data Modeling and Database Systems",
  "Introduction to Business Informatics",
  "Procurement, Purchasing and Distribution",
  "Marketing",
];
